# Generated by Django 3.0.4 on 2020-03-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=4)),
                ('capacity', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'classroom',
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('inst_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=320)),
                ('title', models.CharField(max_length=20)),
                ('dept', models.ForeignKey(db_column='dept', on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Department')),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=320)),
                ('password', models.CharField(max_length=16)),
                ('grade', models.CharField(max_length=10)),
                ('dept', models.ForeignKey(db_column='dept', on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Department')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentFamily',
            fields=[
                ('stud', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='CNS.Student')),
                ('father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('father_job', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_job', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'student_family',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('post_time', models.DateField()),
                ('replyable', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Student')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.CharField(max_length=7)),
                ('semester', models.CharField(max_length=5)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('credit', models.IntegerField()),
                ('building', models.ForeignKey(db_column='building', on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses_building', to='CNS.Classroom')),
                ('dept', models.ForeignKey(db_column='dept', on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Department')),
                ('room_number', models.ForeignKey(db_column='room_number', on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses_room_number', to='CNS.Classroom')),
            ],
            options={
                'db_table': 'course',
                'unique_together': {('cno', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('cno', models.ForeignKey(db_column='cno', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inst_cno', to='CNS.Course')),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Course')),
                ('stud', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Student')),
            ],
            options={
                'db_table': 'student_grade',
                'unique_together': {('stud', 'cno', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('inst', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Instructor')),
                ('proj_number', models.ForeignKey(db_column='proj_number', on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Project')),
            ],
            options={
                'db_table': 'research',
                'unique_together': {('inst', 'proj_number')},
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time', models.DateField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Log')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Student')),
            ],
            options={
                'db_table': 'reply',
                'unique_together': {('user', 'log')},
            },
        ),
        migrations.CreateModel(
            name='InstructorArrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.ForeignKey(db_column='cno', on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Course')),
                ('inst', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Instructor')),
                ('semester', models.ForeignKey(db_column='semester', on_delete=django.db.models.deletion.DO_NOTHING, related_name='inst_semester', to='CNS.Course')),
            ],
            options={
                'db_table': 'instructor_arrangement',
                'unique_together': {('inst', 'cno', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_field', models.CharField(db_column='class', max_length=20)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to='CNS.Student')),
            ],
            options={
                'db_table': 'friendship',
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
