# Generated by Django 3.0.4 on 2020-03-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNS', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructorarrangement',
            unique_together={('inst', 'cno')},
        ),
        migrations.RemoveField(
            model_name='instructorarrangement',
            name='semester',
        ),
    ]
