# Generated by Django 3.0.4 on 2020-03-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CNS', '0002_auto_20200327_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorarrangement',
            name='inst',
            field=models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Instructor'),
        ),
    ]
