# Generated by Django 3.0.4 on 2020-03-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CNS', '0003_auto_20200327_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='stud',
            field=models.ForeignKey(db_column='stud_id', on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Student'),
        ),
    ]
