# Generated by Django 3.0.4 on 2020-03-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CNS', '0004_auto_20200328_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='inst',
            field=models.ForeignKey(db_column='inst_id', on_delete=django.db.models.deletion.DO_NOTHING, to='CNS.Project'),
        ),
        migrations.AlterField(
            model_name='research',
            name='proj_number',
            field=models.ForeignKey(db_column='proj_number', on_delete=django.db.models.deletion.DO_NOTHING, related_name='proj_number', to='CNS.Project'),
        ),
    ]
