# Generated by Django 3.0.4 on 2020-03-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CNS', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
